markdown: rdiscount
permalink: /posts/:title
rdiscount:
  extensions: [smart]

gems:
  - jekyll-sitemap

name: Calvin Giles
url: http://calvingiles.github.io
description: "A Physicist in a world of Coding and Data Science"
twitter: calvingiles
